// frontend/src/components/ChatMessage.tsx
import { Space, Typography } from 'antd'
import MarkdownView from './MarkdownView'
import CitationCard from './CitationCard'
import type { Citation } from '../types'

interface Props {
  role: 'user' | 'assistant'
  content: string
  citations?: Citation[]
  streaming?: boolean
}

export default function ChatMessage({ role, content, citations, streaming }: Props) {
  if (role === 'user') {
    return (
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 16 }}>
        <div
          style={{
            background: '#1677ff',
            color: '#fff',
            padding: '10px 14px',
            borderRadius: 12,
            maxWidth: '70%',
            whiteSpace: 'pre-wrap',
          }}
        >
          {content}
        </div>
      </div>
    )
  }

  return (
    <div style={{ display: 'flex', marginBottom: 16 }}>
      <div
        style={{
          background: '#fff',
          border: '1px solid #f0f0f0',
          borderRadius: 12,
          padding: '10px 14px',
          maxWidth: '85%',
        }}
      >
        {content ? (
          <MarkdownView content={content} />
        ) : (
          <Typography.Text type="secondary">思考中{streaming ? '…' : ''}</Typography.Text>
        )}
        {!!citations?.length && (
          <Space size={[8, 8]} wrap style={{ marginTop: 10 }}>
            {citations.map((c, i) => (
              <CitationCard key={i} index={i} citation={c} />
            ))}
          </Space>
        )}
      </div>
    </div>
  )
}

// frontend/src/components/ChatMessage.vue
<template>
  <div v-if="role === 'user'" style="display: flex; justify-content: flex-end; margin-bottom: 16px">
    <div class="chat-bubble chat-bubble-user">{{ content }}</div>
  </div>
  <div v-else style="display: flex; margin-bottom: 16px">
    <div class="chat-bubble chat-bubble-assistant">
      <MarkdownView v-if="content" :content="content" />
      <span v-else style="color: #999">思考中{{ streaming ? '…' : '' }}</span>
      <div v-if="citations && citations.length" class="citation-row">
        <CitationCard v-for="(c, i) in citations" :key="i" :index="i" :citation="c" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import MarkdownView from './MarkdownView.vue'
import CitationCard from './CitationCard.vue'
import type { Citation } from '../types'

defineProps<{
  role: 'user' | 'assistant'
  content: string
  citations?: Citation[]
  streaming?: boolean
}>()
</script>

<style scoped>
.chat-bubble {
  padding: 10px 14px;
  border-radius: 12px;
  max-width: 85%;
  white-space: pre-wrap;
  word-break: break-word;
}
.chat-bubble-user {
  background: #1677ff;
  color: #fff;
  max-width: 70%;
}
.chat-bubble-assistant {
  background: #fff;
  border: 1px solid #f0f0f0;
}
.citation-row {
  margin-top: 10px;
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}
</style>
