// frontend/src/components/CitationCard.vue
<template>
  <el-tooltip placement="top" effect="dark">
    <template #content>
      <div style="max-width: 320px; max-height: 240px; overflow: auto">
        <div style="font-weight: 600; margin-bottom: 4px">{{ citation.title }}</div>
        <div style="white-space: pre-wrap; font-size: 12px">{{ citation.source_text.slice(0, 400) }}</div>
      </div>
    </template>
    <el-tag :type="tagType" style="cursor: pointer">
      [{{ index + 1 }}] {{ citation.title }}
      <span style="opacity: 0.7; margin-left: 6px">相似度 {{ (citation.similarity * 100).toFixed(1) }}%</span>
    </el-tag>
  </el-tooltip>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Citation } from '../types'

const props = defineProps<{ index: number; citation: Citation }>()

const TAG_TYPES = ['primary', 'cyan', 'info', 'warning', 'danger', 'success'] as const

const tagType = computed(() => TAG_TYPES[props.index % TAG_TYPES.length])
</script>

// frontend/src/components/CitationCard.tsx
import { Tooltip, Tag } from 'antd'
import type { Citation } from '../types'

const TAG_COLORS = ['blue', 'cyan', 'geekblue', 'purple', 'magenta', 'orange', 'gold']

export default function CitationCard({ index, citation }: { index: number; citation: Citation }) {
  const color = TAG_COLORS[index % TAG_COLORS.length]
  return (
    <Tooltip
      title={
        <div style={{ maxWidth: 320, maxHeight: 240, overflow: 'auto' }}>
          <div style={{ fontWeight: 600, marginBottom: 4 }}>{citation.title}</div>
          <div style={{ whiteSpace: 'pre-wrap', fontSize: 12 }}>{citation.source_text.slice(0, 400)}</div>
        </div>
      }
    >
      <Tag color={color} style={{ cursor: 'pointer' }}>
        [{index + 1}] {citation.title}
        <span style={{ opacity: 0.7, marginLeft: 6 }}>
          相似度 {citation.similarity.toFixed(2)}
        </span>
      </Tag>
    </Tooltip>
  )
}
