// frontend/src/layouts/MainLayout.tsx
import { Layout, Menu, Space, Tag, Typography } from 'antd'
import type { MenuProps } from 'antd'
import {
  CalendarOutlined,
  CompassOutlined,
  ControlOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  FileTextOutlined,
  HistoryOutlined,
  HomeOutlined,
  LogoutOutlined,
  MedicineBoxOutlined,
  MessageOutlined,
  ReadOutlined,
  ScheduleOutlined,
  SettingOutlined,
  TeamOutlined,
} from '@ant-design/icons'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { useMemo } from 'react'
import { useAuth } from '../stores/auth'
import { ROLE_COLORS, ROLE_LABELS } from '../types'
import type { Role } from '../types'

const { Header, Sider, Content, Footer } = Layout
type MenuItem = Required<MenuProps>['items'][number]

const COMMON_MENU: MenuItem[] = [
  { key: '/', icon: <DashboardOutlined />, label: '数据仪表盘' },
  { key: '/chat', icon: <MessageOutlined />, label: '智能咨询' },
  { key: '/chat/history', icon: <HistoryOutlined />, label: '咨询历史' },
]

const ROLE_MENUS: Record<Role, MenuItem[]> = {
  patient: [
    ...COMMON_MENU,
    { key: '/patient', icon: <HomeOutlined />, label: '我的健康档案' },
    { key: '/appointments', icon: <CalendarOutlined />, label: '预约挂号' },
  ],
  doctor: [
    ...COMMON_MENU,
    { key: '/doctor/patients', icon: <TeamOutlined />, label: '患者管理' },
    { key: '/doctor/hospitalizations', icon: <MedicineBoxOutlined />, label: '住院信息管理' },
    { key: '/schedule', icon: <ScheduleOutlined />, label: '排班管理' },
    { key: '/kb', icon: <DatabaseOutlined />, label: '知识库管理' },
    { key: '/doctor', icon: <ControlOutlined />, label: '医生工作台' },
  ],
  nurse: [
    ...COMMON_MENU,
    { key: '/nurse', icon: <FileTextOutlined />, label: '护理工作台' },
    { key: '/schedule', icon: <ScheduleOutlined />, label: '排班管理' },
  ],
  public: [
    ...COMMON_MENU,
    { key: '/health', icon: <ReadOutlined />, label: '健康资讯' },
    { key: '/guide', icon: <CompassOutlined />, label: '就诊指南' },
    { key: '/appointments', icon: <CalendarOutlined />, label: '预约挂号' },
  ],
  admin: [
    ...COMMON_MENU,
    { key: '/admin', icon: <SettingOutlined />, label: '系统管理' },
    { key: '/kb', icon: <DatabaseOutlined />, label: '知识库管理' },
  ],
}

export default function MainLayout() {
  const user = useAuth((s) => s.user)
  const logout = useAuth((s) => s.logout)
  const navigate = useNavigate()
  const location = useLocation()

  const items = useMemo(() => {
    if (!user) return COMMON_MENU
    return ROLE_MENUS[user.role] ?? COMMON_MENU
  }, [user])

  // 修复：/chat/history 与 /chat/history/:id 应高亮“咨询历史”而非“智能咨询”
  const selected = useMemo(() => {
    const path = location.pathname
    if (path === '/') return '/'
    const matches = items.filter(
      (i) => i && typeof i === 'object' && 'key' in i && i.key !== '/' &&
        (path === i.key || path.startsWith(String(i.key) + '/')),
    )
    matches.sort((a, b) => String((b as { key: string }).key).length - String((a as { key: string }).key).length)
    return matches.length ? String((matches[0] as { key: string }).key) : path
  }, [items, location.pathname])

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sider theme="dark" width={220}>
        <div
          style={{
            height: 56,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: '#fff',
            fontSize: 18,
            fontWeight: 600,
          }}
        >
          🏥 医智助手
        </div>
        <Menu
          theme="dark"
          mode="inline"
          selectedKeys={[selected]}
          items={items}
          onClick={({ key }) => navigate(key)}
        />
      </Sider>
      <Layout>
        <Header
          style={{
            background: '#fff',
            padding: '0 24px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            boxShadow: '0 1px 4px rgba(0,21,41,0.08)',
          }}
        >
          <Typography.Text strong style={{ fontSize: 16 }}>
            医智助手 · 医疗知识库智能问答
          </Typography.Text>
          <Space size="middle">
            {user && (
              <>
                <Tag color={ROLE_COLORS[user.role]}>
                  {ROLE_LABELS[user.role]} · {user.display_name}
                </Tag>
                <Typography.Link
                  onClick={() => {
                    logout()
                    navigate('/login')
                  }}
                >
                  <LogoutOutlined /> 退出登录
                </Typography.Link>
              </>
            )}
          </Space>
        </Header>
        <Content style={{ margin: 16 }}>
          <Outlet />
        </Content>
        <Footer
          style={{
            textAlign: 'center',
            color: '#999',
            padding: '16px 24px',
            background: '#fff',
            borderTop: '1px solid #f0f0f0',
          }}
        >
          © {new Date().getFullYear()} 安徽医科大学 · 医智助手医疗信息系统教学演示平台 · 内容仅用于健康科普，不构成诊疗建议
        </Footer>
      </Layout>
    </Layout>
  )
}

// frontend/src/layouts/MainLayout.vue
<template>
  <el-container class="layout">
    <el-aside width="220px" class="aside">
      <div class="logo">🏥 医智助手</div>
      <el-menu :default-active="activeMenu" router class="menu" background-color="#001529" text-color="#ffffff80"
        active-text-color="#fff">
        <el-menu-item v-for="item in menus" :key="item.path" :index="item.path">
          <el-icon><component :is="item.icon" /></el-icon>
          <span>{{ item.label }}</span>
        </el-menu-item>
      </el-menu>
    </el-aside>

    <el-container>
      <el-header class="header">
        <span class="header-title">医智助手 · 医疗知识库智能问答</span>
        <span v-if="auth.user" class="header-right">
          <el-tag :type="ROLE_TAG_TYPES[auth.user.role]" size="default">
            {{ ROLE_LABELS[auth.user.role] }} · {{ auth.user.display_name }}
          </el-tag>
          <el-link type="danger" :underline="false" @click="logout">
            <el-icon><SwitchButton /></el-icon>&nbsp;退出登录
          </el-link>
        </span>
      </el-header>

      <el-main class="main">
        <router-view />
      </el-main>

      <el-footer class="footer">
        © {{ year }} 安徽医科大学 · 医智助手医疗信息系统教学演示平台 · 内容仅用于健康科普，不构成诊疗建议
      </el-footer>
    </el-container>
  </el-container>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuth } from '../stores/auth'
import { ROLE_LABELS, ROLE_TAG_TYPES } from '../types'
import type { Role } from '../types'

const auth = useAuth()
const route = useRoute()
const router = useRouter()
const year = new Date().getFullYear()

interface MenuItem {
  path: string
  label: string
  icon: string
}

const COMMON_MENU: MenuItem[] = [
  { path: '/', label: '数据仪表盘', icon: 'Odometer' },
  { path: '/chat', label: '智能咨询', icon: 'ChatDotRound' },
  { path: '/chat/history', label: '咨询历史', icon: 'Clock' },
]

const ROLE_MENUS: Record<Role, MenuItem[]> = {
  patient: [
    ...COMMON_MENU,
    { path: '/patient', label: '我的健康档案', icon: 'Files' },
    { path: '/appointments', label: '预约挂号', icon: 'Calendar' },
  ],
  doctor: [
    ...COMMON_MENU,
    { path: '/doctor/patients', label: '患者管理', icon: 'User' },
    { path: '/doctor/hospitalizations', label: '住院信息管理', icon: 'FirstAidKit' },
    { path: '/schedule', label: '排班管理', icon: 'Calendar' },
    { path: '/kb', label: '知识库管理', icon: 'Collection' },
    { path: '/doctor', label: '医生工作台', icon: 'Monitor' },
  ],
  nurse: [
    ...COMMON_MENU,
    { path: '/nurse', label: '护理工作台', icon: 'Document' },
    { path: '/schedule', label: '排班管理', icon: 'Calendar' },
  ],
  public: [
    ...COMMON_MENU,
    { path: '/health', label: '健康资讯', icon: 'Reading' },
    { path: '/guide', label: '就诊指南', icon: 'Compass' },
    { path: '/appointments', label: '预约挂号', icon: 'Calendar' },
  ],
  admin: [
    ...COMMON_MENU,
    { path: '/admin', label: '系统管理', icon: 'Setting' },
    { path: '/kb', label: '知识库管理', icon: 'Collection' },
  ],
}

const menus = computed<MenuItem[]>(() => {
  if (!auth.user) return COMMON_MENU
  return ROLE_MENUS[auth.user.role] ?? COMMON_MENU
})

// 修复：/chat/history 与 /chat/history/:id 高亮"咨询历史"
const activeMenu = computed(() => {
  const path = route.path
  if (path === '/') return '/'
  const matches = menus.value.filter(
    (i) => i.path !== '/' && (path === i.path || path.startsWith(i.path + '/')),
  )
  matches.sort((a, b) => b.path.length - a.path.length)
  return matches.length ? matches[0].path : path
})

function logout() {
  auth.logout()
  router.push('/login')
}
</script>

<style scoped>
.layout {
  min-height: 100vh;
}
.aside {
  background: #001529;
  overflow: auto;
}
.logo {
  height: 56px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 18px;
  font-weight: 600;
}
.menu {
  border-right: none;
}
.header {
  background: #fff;
  display: flex;
  align-items: center;
  justify-content: space-between;
  box-shadow: 0 1px 4px rgba(0, 21, 41, 0.08);
}
.header-title {
  font-size: 16px;
  font-weight: 600;
}
.header-right {
  display: flex;
  align-items: center;
  gap: 16px;
}
.main {
  margin: 16px;
  background: transparent;
}
.footer {
  text-align: center;
  color: #999;
  background: #fff;
  border-top: 1px solid #f0f0f0;
}
</style>
