// frontend/src/pages/ChatHistoryPage.vue
<template>
  <el-card>
    <template #header>咨询历史</template>
    <div style="display: flex; align-items: center; gap: 12px; margin-bottom: 16px">
      <el-input v-model="q" placeholder="搜索会话标题" clearable style="width: 260px" @keyup.enter="doSearch" />
      <el-button type="primary" plain @click="doSearch">搜索</el-button>
      <el-tag>{{ total }} 条</el-tag>
    </div>
    <el-table :data="items" v-loading="loading" row-key="id">
      <el-table-column label="标题" min-width="200">
        <template #default="{ row }">
          <strong><el-icon style="margin-right: 6px"><Message /></el-icon>{{ row.title }}</strong>
        </template>
      </el-table-column>
      <el-table-column label="知识库" prop="kb_name" width="180">
        <template #default="{ row }">{{ row.kb_name || '-' }}</template>
      </el-table-column>
      <el-table-column label="消息数" prop="message_count" width="90" align="center" />
      <el-table-column label="更新时间" prop="updated_at" width="170" />
      <el-table-column label="操作" width="230">
        <template #default="{ row }">
          <el-button size="small" type="primary" link @click="router.push(`/chat?conversation=${row.id}`)">
            继续咨询
          </el-button>
          <el-button size="small" type="primary" link @click="router.push(`/chat/history/${row.id}`)">
            查看记录
          </el-button>
          <el-button size="small" type="danger" link @click="remove(row.id)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
    <el-pagination v-model:current-page="page" :page-size="10" :total="total" layout="prev, pager, next, total"
      style="margin-top: 16px; justify-content: flex-end" @current-change="load" />
  </el-card>
</template>

<script setup lang="ts">
import {onMounted, ref} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessage, ElMessageBox} from 'element-plus'
import {chatApi} from '@/api/endpoints'
import type {Conversation} from '@/types'

const router = useRouter()
const items = ref<Conversation[]>([])
const total = ref(0)
const q = ref('')
const page = ref(1)
const loading = ref(false)

async function load() {
  loading.value = true
  try {
    const data = await chatApi.conversations({ q: q.value, page: page.value, page_size: 10 })
    items.value = data.items
    total.value = data.total
  } catch (e) {
    ElMessage.error((e as Error).message)
  } finally {
    loading.value = false
  }
}

onMounted(load)

function doSearch() {
  page.value = 1
  load()
}

async function remove(id: string) {
  try {
    await ElMessageBox.confirm('确定删除该会话？', '提示', { type: 'warning' })
    await chatApi.remove(id)
    ElMessage.success('已删除')
    load()
  } catch (e) {
    if (e !== 'cancel' && e !== 'close') ElMessage.error((e as Error).message)
  }
}
</script>

// frontend/src/pages/ChatHistoryPage.tsx
import { useEffect, useState } from 'react'
import { Button, Card, Input, Space, Table, Tag, App, Typography } from 'antd'
import { DeleteOutlined, MessageOutlined, RightOutlined } from '@ant-design/icons'
import type { ColumnsType } from 'antd/es/table'
import { useNavigate } from 'react-router-dom'
import { chatApi } from '../api/endpoints'
import type { Conversation } from '../types'

export default function ChatHistoryPage() {
  const [items, setItems] = useState<Conversation[]>([])
  const [total, setTotal] = useState(0)
  const [q, setQ] = useState('')
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)
  const { message: toast } = App.useApp()
  const navigate = useNavigate()

  const load = () => {
    setLoading(true)
    chatApi
      .conversations({ q, page, page_size: 10 })
      .then((data) => {
        setItems(data.items)
        setTotal(data.total)
      })
      .catch((e) => toast.error((e as Error).message))
      .finally(() => setLoading(false))
  }

  useEffect(load, [q, page, toast])

  const remove = async (id: string) => {
    try {
      await chatApi.remove(id)
      toast.success('已删除')
      load()
    } catch (e) {
      toast.error((e as Error).message)
    }
  }

  const columns: ColumnsType<Conversation> = [
    {
      title: '标题',
      dataIndex: 'title',
      ellipsis: true,
      render: (v: string) => (
        <Typography.Text strong>
          <MessageOutlined style={{ marginRight: 6 }} />
          {v}
        </Typography.Text>
      ),
    },
    { title: '知识库', dataIndex: 'kb_name', width: 180, render: (v?: string) => v || '-' },
    { title: '消息数', dataIndex: 'message_count', width: 90, align: 'center' },
    { title: '更新时间', dataIndex: 'updated_at', width: 170 },
    {
      title: '操作',
      width: 220,
      render: (_, record) => (
        <Space>
          <Button size="small" type="link" icon={<RightOutlined />} onClick={() => navigate(`/chat?conversation=${record.id}`)}>
            继续咨询
          </Button>
          <Button size="small" type="link" onClick={() => navigate(`/chat/history/${record.id}`)}>
            查看记录
          </Button>
          <Button size="small" danger type="text" icon={<DeleteOutlined />} onClick={() => remove(record.id)} />
        </Space>
      ),
    },
  ]

  return (
    <Card title="咨询历史">
      <Space style={{ marginBottom: 16 }}>
        <Input.Search
          placeholder="搜索会话标题"
          allowClear
          style={{ width: 260 }}
          onSearch={(v) => {
            setPage(1)
            setQ(v)
          }}
        />
        <Tag>{total} 条</Tag>
      </Space>
      <Table
        rowKey="id"
        columns={columns}
        dataSource={items}
        loading={loading}
        pagination={{
          current: page,
          pageSize: 10,
          total,
          onChange: setPage,
          showSizeChanger: false,
        }}
      />
    </Card>
  )
}
