// frontend/src/pages/LoginPage.vue
<template>
  <div class="login-wrap">
    <el-card class="login-card">
      <div class="brand">
        <div style="font-size: 40px">🏥</div>
        <h2 style="margin: 8px 0 4px">医智助手</h2>
        <p style="color: #999; margin: 0">医疗知识库智能问答系统</p>
      </div>
      <el-form :model="form" label-position="top" @submit.prevent="onSubmit">
        <el-form-item label="用户名">
          <el-input v-model="form.username" placeholder="演示账号：patientdemo / doctordemo / admindemo"
            autocomplete="username" />
        </el-form-item>
        <el-form-item label="密码">
          <el-input v-model="form.password" type="password" placeholder="演示密码：demo123" show-password
            autocomplete="current-password" @keyup.enter="onSubmit" />
        </el-form-item>
        <el-button type="primary" size="large" style="width: 100%" :loading="loading" @click="onSubmit">
          登录
        </el-button>
        <div style="text-align: center; margin-top: 16px">
          <span style="color: #999">还没有账号？</span>
          <el-link type="primary" @click="router.push('/register')">立即注册</el-link>
        </div>
      </el-form>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import {reactive, ref} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessage} from 'element-plus'
import {useAuth} from '../stores/auth'

const auth = useAuth()
const router = useRouter()
const loading = ref(false)
const form = reactive({ username: '', password: '' })

async function onSubmit() {
  if (!form.username || !form.password) {
    ElMessage.warning('请输入用户名和密码')
    return
  }
  loading.value = true
  try {
    await auth.login(form.username, form.password)
    ElMessage.success('登录成功')
    router.push('/')
  } catch (e) {
    ElMessage.error((e as Error).message)
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-wrap {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #e8f4fd 0%, #f0fff4 100%);
}
.login-card {
  width: 380px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.08);
}
.brand {
  text-align: center;
  margin-bottom: 24px;
}
</style>

// frontend/src/pages/LoginPage.tsx
import { Button, Card, Form, Input, App, Typography } from 'antd'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../stores/auth'

interface FormValues {
  username: string
  password: string
}

export default function LoginPage() {
  const login = useAuth((s) => s.login)
  const navigate = useNavigate()
  const { message } = App.useApp()

  const onFinish = async (values: FormValues) => {
    try {
      await login(values.username, values.password)
      message.success('登录成功')
      navigate('/')
    } catch (e) {
      message.error((e as Error).message)
    }
  }

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'linear-gradient(135deg, #e8f4fd 0%, #f0fff4 100%)',
      }}
    >
      <Card style={{ width: 380, boxShadow: '0 8px 24px rgba(0,0,0,0.08)' }}>
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <div style={{ fontSize: 40 }}>🏥</div>
          <Typography.Title level={3} style={{ marginTop: 8, marginBottom: 4 }}>
            医智助手
          </Typography.Title>
          <Typography.Text type="secondary">医疗知识库智能问答系统</Typography.Text>
        </div>
        <Form<FormValues> layout="vertical" onFinish={onFinish}>
          <Form.Item name="username" label="用户名" rules={[{ required: true, message: '请输入用户名' }]}>
            <Input placeholder="演示账号：patientdemo / doctordemo / admindemo" autoComplete="username" />
          </Form.Item>
          <Form.Item name="password" label="密码" rules={[{ required: true, message: '请输入密码' }]}>
            <Input.Password placeholder="演示密码：demo123" autoComplete="current-password" />
          </Form.Item>
          <Button type="primary" htmlType="submit" block size="large">
            登录
          </Button>
          <div style={{ textAlign: 'center', marginTop: 16 }}>
            <Typography.Text type="secondary">还没有账号？</Typography.Text>{' '}
            <Link to="/register">立即注册</Link>
          </div>
        </Form>
      </Card>
    </div>
  )
}
